---
#author:zhang
- name: "install haproxy"
  package:
    name: haproxy
    state: present

- name: "gen haproxy.cfg"
  template:
    src: "haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
  notify:
    - restart haproxy
