---
#author:zhang
- import_tasks: coredns.yml
  tags:
    - coredns

- import_tasks: metrics-server.yml
  when: metrics_server.enabled == true
  tags:
    - metrics-server

- import_tasks: nodelocaldns.yml
  when: nodelocaldns.enabled == true
  tags:
    - nodelocaldns

- import_tasks: helm.yml
  when: helm.enabled == true
  tags:
    - helm

#- import_tasks: nvidia-device-plugin.yml
 # when: nvidia_device_plugin.enabled == true
 # tags:
  #  - nvidia_device_plugin
