---
- name: "Generate nodelocaldns yaml"
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - {src: "nodelocaldns.yaml.j2", dest: "/tmp/nodelocaldns.yaml"}
  tags: nodelocaldns

- name: "Deploy nodelocaldns"
  shell: "kubectl apply -f /tmp/nodelocaldns.yaml"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: nodelocaldns
