---
#author:zhang

- name: "set hostname"
  hostname:
    #hostname|quote是一个过滤器（filter），用于将主机名（hostname）转换为引号包围的字符串，以便在模板或其他字符串中进行使用
    name: "{{ hostname|quote }}"
    use: systemd
  tags: hostname

- name: "set env"
  copy:
    src: "ipenv.sh"
    dest: "/etc/profile.d/"
  tags: os_env

- name: "set timezone"
  timezone:
    name: Asia/Shanghai

- name: "install chrony"
  package:
    name: chrony
    state: present
  when:
    - ansible_os_family in ['RadHat','AlmaLinux'.'Rocky']
  tags: ntp

- name: "set chrony.service"
  copy:
    src: "chrony.conf"
    dest: "/etc/chrony.conf"
  #notify作用是在上面这个任务完成后通知下面任务执行，将其添加到任务队列中
  notify:
    - restart chrony
  when:
    - ansible_os_family in ['RedHat', 'AlmaLinux', 'Rocky']
  tags: ntp


- name: "set systemd-timesyncd.service"

  copy:
    src: "timesyncd.conf"
    dest: "/etc/systemd/timesyncd.conf"


  notify:
    - restart systemd-timesyncd
  when:
    - ansible_os_family in ["Debian"]
  tags: ntp



- name: "Disable swap"
  shell: swapoff -a


  tags: swap


- name: "Remove swapfile from /etc/fstab"
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none
  tags: swap


- name: “disable selinux”
  selinux:
    state: disabled
  when:
    - ansible_os_family in ['RedHat', 'AlmaLinux', 'Rocky']
  tags: selinux

- name: "get firewalld is installed"

  command: whereis ffirewalld
  register: firewalld_state


- name: "stop firewalld"
  when: "'/usr/sbin/firewalld' in firewalld_state.stout"
  systemd:
    name: firewalld
    enabled: no
    #标记任务，并强制运行任务
    masked: false
    state: stopped
  tags: firewalld




- name: "set ssh"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "UseDNS", line: "UseDNS no" }
    - { regexp: "ClientAliveInterval", line: "ClientAliveInterval 600" }
    - { regexp: "ClientAliveCountMax", line: "ClientAliveCountMax 2" }
    - { regexp: "AddressFamily", line: "AddressFamily inet" }
    - { regexp: "PermitRootLogin", line: "PermitRootLogin yes" }
    - { regexp: "PermitEmptyPasswords", line: "PermitEmptyPasswords no" }
    - { regexp: "PasswordAuthentication", line: "PasswordAuthentication no" } 



  notify:
    - restart sshd
  tags: sshd


- name: "Set password expiration time"
  lineinfile:
    dest: "/etc/login.defs"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "PASS_MIN_DAYS", line: "PASS_MIN_DAYS 0" }
    - { regexp: "PASS_MAX_DAYS", line: "PASS_MAX_DAYS 99999" }
  tags: passwd

- name: "Set password complexity"
  lineinfile:
    dest: "/etc/security/pwquality.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "minlen", line: "minlen=10" }
    - { regexp: "minclass", line: "minclass=3" }
  when:
    - ansible_os_family in ['RedHat', 'AlmaLinux', 'Rocky']
  tags: passwd

- name: "Set password remember"
  replace:
    path: "{{ item.path }}"
    regexp: "use_authtok$"
    replace: "use_authtok remember=5"
  with_items:
    - { path: "/etc/pam.d/password-auth" }
    - { path: "/etc/pam.d/system-auth" }
  when:
    - ansible_os_family in ['RedHat', 'AlmaLinux', 'Rocky']
  tags: passwd

- name: "Set limits"
  pam_limits:
    dest: "/etc/security/limits.conf"
    domain: '{{ item.limit_domain }}'
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  with_items:
    - { limit_domain: 'root',limit_type: 'soft',limit_item: 'nofile', value: '655360' }
    - { limit_domain: 'root',limit_type: 'hard',limit_item: 'nofile', value: '655360' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'core', value: '0' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'core', value: '0' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'nproc', value: '655360' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'nproc', value: '655360' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'stack', value: 'unlimited' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'stack', value: 'unlimited' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'nofile', value: '655360' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'nofile', value: '655360' }
  tags: limits

- name: "Set systemd limits"
  lineinfile:
    dest: "/etc/systemd/system.conf"
    line: "{{ item.line }}"
    state: present
  with_items:
    - {line: 'DefaultLimitNOFILE=65535' }
    - {line: 'DefaultLimitNPROC=65535' }
  tags: limits

- name: "Modify sysctl"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_items:
    - {name: 'kernel.sysrq',value: '1' }
    - {name: 'vm.swappiness ',value: ' 0' }
    - {name: 'net.ipv4.ip_forward',value: '1' }
    - {name: 'net.ipv4.neigh.default.gc_stale_time',value: '120' }
    - {name: 'net.ipv4.conf.all.rp_filter',value: '0' }
    - {name: 'net.ipv4.conf.default.rp_filter',value: '0' }
    - {name: 'net.ipv4.conf.default.arp_announce ',value: ' 2' }
    - {name: 'net.ipv4.conf.lo.arp_announce',value: '2' }
    - {name: 'net.ipv4.conf.all.arp_announce',value: '2' }
    - {name: 'net.ipv4.tcp_max_tw_buckets',value: '5000' }
    - {name: 'net.ipv4.tcp_syncookies ',value: ' 1' }
    - {name: 'net.ipv4.tcp_max_syn_backlog ',value: ' 1024' }
    - {name: 'net.ipv4.tcp_synack_retries ',value: ' 2' }
    - {name: 'net.ipv4.tcp_fin_timeout',value: '30' }
    - {name: 'net.ipv4.tcp_keepalive_time',value: '600' }
    - {name: 'net.ipv4.tcp_keepalive_intvl',value: '30' }
    - {name: 'net.ipv4.tcp_keepalive_probes',value: '10' }
    - {name: 'net.ipv4.ip_local_port_range',value: '20000 60999' }
  tags: sysctl

- name: "Install base application"
  package:
    name:
      - vim
      - mtr
      - tar
      - curl
      - wget
      - lsof
      - unzip
      - lrzsz
      - rsync
      - telnet
      - bash-completion
      - net-tools
    state: present
  tags: install_app

- name: "Install base application"
  package:
    name:
      - nmap-ncat
      - yum-utils
      - nfs-utils
    state: present
  when:
    - ansible_os_family in ['RedHat', 'AlmaLinux', 'Rocky']
  tags: install_app

- name: "Install base application"
  package:
    name:
      - nmap
      - nmap-common
      - nfs-common
    state: present
  when:
    - ansible_os_family in ["Debian"]
  tags: install_app
    
